export PLATFORM="$(uname)"
if [[ "$PLATFORM" != "Darwin" ]]; then
    export OS_RELEASE=$(grep "^NAME" /etc/os-release | cut -d = -f 2 | tr -d '"')
fi

# PATH
export PATH=$HOME/.local/bin:$HOME/.nix-profile/bin:$PATH
export FPATH=$HOME/.local/share/zsh/completions:$HOME/.nix-profile/share/zsh/site-functions:$ANTIGEN_PATH/src/:$FPATH

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"

# HISTORY
setopt SHARE_HISTORY
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_ALL_DUPS
export HISTSIZE=50000
export SAVEHIST=50000

# ZSHCONFIG
export ZDOTDIR="$HOME/.config/zsh"
export HISTFILE="$HOME/.zsh_history"

# EDITOR
export EDITOR="nvim"

# BROWSER
export BROWSER="firefox -private-window"

# cargo
source "$HOME/.cargo/env"
. "$HOME/.cargo/env"

# extras
[[ -f ~/.extras.zsh ]] && source ~/.extras.zsh
