export PLATFORM="$(uname)"
if [[ "$PLATFORM" != "Darwin" ]]; then
    export OS_RELEASE=$(grep "^NAME" /etc/os-release | cut -d = -f 2 | tr -d '"')
fi

# PATH
export PATH=$HOME/.local/bin:$HOME/.nix-profile/bin:$PATH
export FPATH=$HOME/.local/share/zsh/completions:$HOME/.nix-profile/share/zsh/site-functions:$ANTIGEN_PATH/src/:$FPATH

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"

# ZSHCONFIG
export ZDOTDIR="$HOME/.config/zsh"
export HISTFILE="$HOME/.zsh_history"

# EDITOR
export EDITOR="nvim"

# BROWSER
export BROWSER="firefox -private-window"
